import Navbar from './Components/Navbar'
import './globals.css'
import { Raleway } from 'next/font/google'

const raleway = Raleway({
   subsets: ['latin'],
   weight:['100','200','300','400','500','600','700','800'],
   variable : '--font-raleway',
   })

export const metadata = {
  title: 'PhotoGraphy Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} font-raleway`}>
       <Navbar/>
        {children}
       
        </body>
    </html>
  )
}
